- name: Create daemon.json
  file:
    path: "/etc/docker/daemon.json"
    state: touch

- name: Update daemon.json
  file:
    path: "/etc/docker/daemon.json"
    content: '{"insecure-registries" : [":5000"]}'

- name: Reset daemon
  command: "service docker restart"

- name: Check docker info
  comand: "docker info"