- name: get jenkins image
  docker_image:
    name: "{{image}}"
    source: pull
  loop: "{{docker_image.image}}"

- name: running jenkins container
  docker_container:
    name: jenkins
    image: "{{docker_image.image}}"
    state: started
    ports:
      - "8080:8080"

  